### ISSUE TITLE
Ability to use and deduct Play Coins

### ISSUE THREAD

**Issue by Nehemek** [lovebrew/LovePotion#127]
PlayCoins are a feature even official games did not make a lot of use of, yet they offer very interesting dynamics for games that I have not seen in any other system (provided you don't increase them via hacks). Two functions would bee needed to make use of this, one to get the amount of coins available and one to set them, that's all.

**Comment by TurtleP** [comment]
I'm not entirely against the idea, but I also have no idea what kind of purpose this would create. Play coins themselves don't do much as far as I can remember.

**Comment by Nehemek** [comment]
In mobile games you create these "play cycles" by adding timers to things i.e. "3 hours to open a chest", "new life in 15 minutes". Basically you are creating an incentive for the user to return to your game after some time and not burn through all the content in one sitting.

Sure you could tie a timer like that to the OS' time but that's easy to change (and thus mobile games use a server to track the time), playcoins offer a dynamic in which said mechanics could be implemented which require actual time to pass (going around with your console in your pocket). The counter is not as easy to change either (well if you have CFW I guess but still, is not an actual console function).

**Comment by TurtleP** [comment]
What about an instance of someone else using Play Coins to do the same thing? You would easily lose track of how many *your* game left off with (either obtained or lost via purchases). However, I think the solution to give would be a realtime save/load system to ensure *your* game's Play Coin data is persistent vs someone else's. Thoughts?

**Comment by Nehemek** [comment]
Oh no, don't get me wrong, Play Coins are _not_ timers, critical game functions cannot be tied to them, they are used for bonus/side things/extra items. They _do_ represent a passage of time but they are not always _equal_ amounts of time.

Thus you deduct them, and check if the user has enough, not keep track of how many at x/y moment.

**Comment by TurtleP** [comment]
Ah okay, that makes sense.

**Comment by TurtleP** [comment]
Implemented in commit 90cd52d
