### ISSUE TITLE
Ability to get friendcode

### ISSUE THREAD

**Issue by Nehemek** [lovebrew/LovePotion#128]
The way friendcodes work on the consoles are very interesting. They aren't particularly easy to change and thus can serve as a simple id system. This can come in handy when working with online leaderboards particularly for tracking or bans, no need to integrate some sort of account system or deal with usernames which can be repeated.

A simple function that returns a string would suffice.

**Comment by TurtleP** [comment]
I like the idea, although I want to be able to implement this on both consoles. Right now there's no way to do it on Switch, but if I find a way, I will add it.

**Comment by TurtleP** [comment]
Good news! I've found a way to get the Switch friend code. However, this might require waiting for the next libnx release if it gets into the library on time.

![image](https://user-images.githubusercontent.com/6239208/113379222-eb52d480-9346-11eb-9488-b68d6aef2cec.png)

**Comment by TurtleP** [comment]
partially implemented in 11477c5da0922dd4d2ae0b8dfaa1b79d7a295f5d -- waiting for the [pull request](https://github.com/switchbrew/libnx/pull/539) to be approved and merged (and then the next libnx release)

**Comment by TurtleP** [comment]
libnx 4.1.0 has just released with this functionality. Once physics is implemented, I will add this.
