### ISSUE TITLE
[BUG] Source issues

### ISSUE THREAD

**Issue by HTV04** [lovebrew/LovePotion#133]
### **Describe the bug**
Source:stop() may be working incorrectly, causing other Sources to either not play or causing LovePotion to freeze. Source:stop() can especially cause issues if it is called before Source:play().

### **Expected behavior**
Sources should stop and play without issues, regardless of the order Source:stop() and Source:play() are called.

### **System Info [Please complete the following information]:**
 - System: Switch
 - Firmware version: 11.0.1
 - CFW w/ version: Atmosphère 0.18.1
 - Method of execution: title takeover
 - LÖVE Potion version: 2.0.0

**Comment by TurtleP** [comment]
I think it's been fixed in a2b9c34 (message box dev branch). Gonna need to do some more testing to be sure. Do you have some sample code I can use?

**Comment by TurtleP** [comment]
It's definitely been fixed, but there's still some audio issues, as was mentioned by you in DM. I'm not sure how much better I could make the responsiveness yet, but I'll continue working on this as I can. For now, since this specifically is fixed, I'll close it.
