### ISSUE TITLE
Add support for drawing roundrectangles

### ISSUE THREAD

**Issue by Nehemek** [lovebrew/LovePotion#138]
**Is your feature request related to a problem? Please describe.**
The roundrectangle options for the function love.graphics.rectangle are missing.

**Describe the solution you'd like**
Make the function love.graphics.rectangle consistent with Löve by adding the function variant: 
_love.graphics.rectangle( mode, x, y, width, height, rx, ry, segments )_
https://love2d.org/wiki/love.graphics.rectangle

**Describe alternatives you've considered**
I have tried using premade graphics, drawing two crossed rectangles and/or drawing lines at the sides of a rectangle. Neither of these approaches are efficient or perfect:
1. Using premade graphics require complicated methods for dynamic sizing.
2. Crossing rectangles work for small radii but break when requiring transparency.
3. Drawing lines next to a rectangle require many more draw calls particularly for big corner radii.

**Additional notes**
Roundrectangles are a simple and easy way to build good looking user interfaces (which is what I want them for), particularly with current design trends.

**Comment by TurtleP** [comment]
Fixed with 65e5ca7
