### ISSUE TITLE
[BUG] Source:play() sometimes doesn't output audio

### ISSUE THREAD

**Issue by HTV04** [lovebrew/LovePotion#140]
### **Describe the bug**
Sometimes when Source:play() is called, the source's audio is not output. However, functions checking the current status of the source behave as if the audio is playing, i.e. Source:tell(), Source:isPlaying(), etc.

### **Expected behavior**
Source:play() should always output the source's audio.

### **System Info [Please complete the following information]:**
 - System: Switch
 - Firmware version: 11.0.1
 - CFW w/ version: Atmosphère 0.18.1
 - Method of execution: title takeover
 - LÖVE Potion version: 2.0.0

**Comment by TurtleP** [comment]
Have you tested this on the more recent nightlies (from GitHub Actions that were successful)? There were some odd inconsistencies between how 3DS handled things internally versus Switch which I fixed up.

**Comment by HTV04** [comment]
I just tested 2.1.0, but the audio bug is still there.
