### ISSUE TITLE
[BUG] Drawing a roundrectangle with transparency has alpha blending issues.

### ISSUE THREAD

**Issue by Nehemek** [lovebrew/LovePotion#143]
### **Describe the bug**
When drawing a roundrectangle with any type of transparency the different components that make up a roundrectangle get a cummulative alpha blending.

### **Expected behavior**
Alpha across a roundrectangle should be uniform.

### **Relevant Code To Reproduce**
``
love.graphics.setColor(1,1,1,.35)
love.graphics.rectangle("fill",2,2,36,36,4,4)
``

### **[Screenshots]**
![roundrectanglealpga](https://user-images.githubusercontent.com/66986051/120704297-0abbca00-c47c-11eb-9dc9-661d62d55084.png)

### **System Info [Please complete the following information]:**
System: 3ds v11.14.0-46U
CFW: Luma v10.2.1
Method of execution: Homebrew App
LÖVE Potion version: Artifact generated by commit #dbe48f

**Comment by TurtleP** [comment]
Fixed in 2b7c0e75
