### ISSUE TITLE
Error thrown when attempting to use love.graphics.clear() with a table as input.

### ISSUE THREAD

**Issue by Phoenix-Flare** [lovebrew/LovePotion#146]
The expected behavior is that it accepts the table as input just as it would in Love2D. There isn't much to explain with this.

Issue tested on:
System: 3ds v11.14.0-46U
CFW: Luma v10.2.1
Method of execution: Homebrew App
LÖVE Potion version: 2.0.0

**Comment by TurtleP** [comment]
Should be easy to fix, just have to finish the physics module first, though :p

**Comment by TurtleP** [comment]
Somewhat fixed in f3e7c1e -- It only supports a single Canvas for now. I really need to update the Canvas stuff to allow multiple Canvases like LÖVE does at some point.
