### ISSUE TITLE
[BUG] Circle render issues

### ISSUE THREAD

**Issue by Phoenix-Flare** [lovebrew/LovePotion#150]
### **Describe the bug**
Circles are rendering as filled regardless of the first parameter provided.

### **Expected behavior**
When the first parameter supplied is "line", the circle should not be filled.

### **Relevant Code To Reproduce**
love.graphics.circle("line", 160, 120, 60)

### **System Info:**
 - System: 3DS
 - Firmware version: v11.14.0-46U
 - CFW w/ version: Luma3DS v10.2.1
 - Method of execution: Homebrew Launcher
 - LÖVE Potion version: Release 2.1.0

**Comment by TurtleP** [comment]
Fixed in a40577031850bc5d5fb2a772cd6147aacc98351d. Release updated accordingly.
