### ISSUE TITLE
[Bug] wrap_window.lua calls love.draw()

### ISSUE THREAD

**Issue by HTV04** [lovebrew/LovePotion#154]
### Software Version

2.2.0 (Latest)

### What Happened?

When launching LOVEPotion before the save directory is created, LOVEPotion will not look for files in the game directory and in most cases will throw an error about missing files.

### What was Expected?

The game directory should be mounted even if the save directory hasn't been mounted yet.

### Code to Reproduce

```Lua
N/A
```

### Console

Nintendo Switch

### Firmware Version(s)

12.0.1

### Custom Firmware Version

0.19.3

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
The save directory is only created when a file is written. It will not be made otherwise. This is also how it behaves in normal LÖVE.

What specifically were you doing that caused this?

**Comment by HTV04** [comment]
> The save directory is only created when a file is written. It will not be made otherwise. This is also how it behaves in normal LÖVE.
> 
> What specifically were you doing that caused this?

I know, but if the directory doesn't exist yet, for whatever reason, LOVEPotion won't be able to load files from the game directory.

This might be another issue I'm overseeing, so let me know if you're able to reproduce this.

**Comment by HTV04** [comment]
Did some more testing, might be worth nothing that the error occurred starting with love.graphics.setFont() in my game. After the save directory was created, there was no longer an error with that function.

**Comment by TurtleP** [comment]
If it's an error from the blue screen or from atmosphere, please attach the proper files so I can evaluate them.

You can save the blue screen error by pressing 'a', otherwise atmosphere has crash reports under '/atmosphere/crash_reports'

**Comment by HTV04** [comment]
[love_error_171710_080221.txt](https://github.com/lovebrew/LovePotion/files/6919688/love_error_171710_080221.txt)

Source: https://github.com/HTV04/funkin-rewritten/tree/1ea915105023dfe9b96836231c4f9a55f433558d

**Comment by TurtleP** [comment]
I also noticed that your `font` variable is global. Could you check your source code that this isn't somehow setting this to `nil`? I'm not sure how this would really affect game directory mounting, honestly. I'll try to investigate more this week, though I'm visiting family so I don't know how busy I'll be.

**Comment by HTV04** [comment]
> I also noticed that your `font` variable is global. Could you check your source code that this isn't somehow setting this to `nil`? I'm not sure how this would really affect game directory mounting, honestly. I'll try to investigate more this week, though I'm visiting family so I don't know how busy I'll be.

The `font` variable doesn't appear to be changed before or after its initialization with the love.graphics.setFont() function. After the `save` directory is created, the error goes away, so maybe LovePotion is trying to look in the `save` directory and failing somehow? What's even weirder is that the save directory gets created before FNFR reaches the error because of the settings initialization, but after restarting it, the error goes away.

**Comment by TurtleP** [comment]
I'll have to look into the actual LÖVE source code again, I suppose. I remember having a bit of trouble following *something* with making the game and directories work, but I'm not sure what. It definitely shouldn't be behaving like this, though, of course.

**Comment by TurtleP** [comment]
Well, I tried this with my own console, latest developer build on hand. I've not changed anything related to fonts. I made a minimal test case:

```lua
function love.load()
    font = love.graphics.newFont("VCR_Mono.ttf", 24)
end

function love.draw()
    love.graphics.setFont(font)
    love.graphics.print("Hello World")
end

function love.gamepadpressed(_, button)
    if button == "start" then
        love.event.quit()
    end
end
```

I'm not sure what's going on with your game, but it seems fine with this. 

I also double checked that I have no save directory: 
![image](https://user-images.githubusercontent.com/6239208/128636879-6181bf73-c4c0-4b23-8ca3-d7274a821cac.png)

**Comment by HTV04** [comment]
What happens if you write a file before loading the font?

**Comment by TurtleP** [comment]
```lua
function love.load()
    love.filesystem.write("test.txt", "yeet")
    font = love.graphics.newFont("VCR_Mono.ttf", 24)
end

function love.draw()
    love.graphics.setFont(font)
    love.graphics.print("Hello World")
end

function love.gamepadpressed(_, button)
    if button == "start" then
        love.event.quit()
    end
end
```

It works perfectly fine.

![image](https://user-images.githubusercontent.com/6239208/128639322-fe8363fa-fcab-4fba-88a3-87e3ea778e3c.png)

**Comment by HTV04** [comment]
Seems like the culprit might have strangely been love.graphics.showMessageBox, because after removing that from my code, the bug disappears. What happens if you call showMessageBox before the other functions in love.load?

**Comment by TurtleP** [comment]
Hm, interesting. Where exactly was the line of code you mention? Because there is a setFont call for its own text to render, but it will reset the font to whatever was last set. It might be a slight stupid mistake on my end if I haven't followed how `getFont` works properly.

Though I do believe that all it does internally is make a new default font if not available, set that, and return it. I'll have to double check this, of course.

**Comment by HTV04** [comment]
https://github.com/HTV04/funkin-rewritten/blob/a463c35ef5dce779c51c73ced6d3e9f2a782dff5/src/love/main.lua#L85

**Comment by HTV04** [comment]
I believe I found the issue. Looks like the wrap_window.lua script calls love.draw() and since it wasn't fully prepared by the time I called it in my script, it threw the error I've been getting.

Since message boxes can often be called during the loading process of a game, maybe a good workaround would be to avoid calling love.draw() or other love functions set by the developer.

**Comment by TurtleP** [comment]
Going to close this for now, we can discuss it more in #161
