### ISSUE TITLE
[Feature Request]: Make each shoulder button a GamepadButton instead of a GamepadAxis

### ISSUE THREAD

**Issue by HTV04** [lovebrew/LovePotion#155]
### Enhancement Details

The shoulder buttons (ZL and ZR) on all of the Switch's controllers are digital, not analog, but LovePotion still classifies each of them as a GamepadAxis.

### Solution

ZL and ZR should each be changed to a GamepadButton instead, simplifying their usage.

### Additional Context

Making ZL and ZR each a GamepadButton could simplify their usage by exposing that their values are purely digital since they only have two states, pressed, and not pressed, unlike a normal analog trigger that returns how far it's pressed down. Perhaps their values could be named "lefttrigger" and "righttrigger."

The only known Switch-compatible controller that does return analog shoulder button values is the GameCube controller, although I'm unsure if LovePotion supports it.

**Comment by TurtleP** [comment]
Although the buttons may be digital, it really only makes sense to keep them as-is. The buttons, sticks, etc are mapped to be like like how they are on the LÖVE wiki. This is not only to maintain proper compatibility, but logically it makes proper sense [as defined here](https://love2d.org/wiki/GamepadAxis).

Think about it like with touch events: LÖVE knows there's some systems that are *not* pressure sensitive, so it will only pass either 0 or 1 when pressing/releasing a touch and not an in-between float.

As for the Gamecube controller, I don't believe it's supported, but I could be wrong. I don't have the hardware to test that.
