### ISSUE TITLE
[Bug]: love.graphics.line() fails to handle more than two coordinate pairs properly

### ISSUE THREAD

**Issue by Phoenix-Flare** [lovebrew/LovePotion#157]
### Software Version

2.2.0 (Latest)

### What Happened?

The engine drew a line between each pair of X, Y coordinates. (i.e. a line between [x1, y1] and [x2, y2], followed by a line between [x3, y3] and [x4, y4])

### What was Expected?

The engine should draw a line from each point to the next in sequence. (i.e. [x1, y1] to [x2, y2] to [x3, y3]... etc)

### Code to Reproduce

```Lua
love.graphics.line(100, 100, 100, 200, 200, 200, 200, 100, 100, 100) --Should draw a 100px*100px square with the upper left corner at (100, 100)
```

### Console

Nintendo 3DS

### Firmware Version(s)

11.14.0-46U

### Custom Firmware Version

10.2.1

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
fixed on commit 9058a8dba0af02d5f07440b2821a0feb12ba8849 (dev/update-defines branch)
