### ISSUE TITLE
[Feature Request]: SpriteBatch

### ISSUE THREAD

**Issue by fontire** [lovebrew/lovepotion#159]
### Enhancement Details

Add SpriteBatch 

### Solution

Add love.graphics SpriteBatch support

### Additional Context

I know this is on the "To do" but I wanted to give it a +1.

**Comment by TurtleP** [comment]
It's been a long time, but I'm working on this in #177.

**Comment by TurtleP** [comment]
This took 3 years, but it's working in 3.0. Currently it's not released with the feature, but closing this as done.

Hopefully it was worth the wait, but I also apologize for the fact it took so long.
