### ISSUE TITLE
[Bug]: Something about not setting fonts

### ISSUE THREAD

**Issue by piepie62** [lovebrew/LovePotion#162]
### Software Version

2.2.0 (Latest)

### What Happened?

Turtle asked me to report this line because new phone and laziness https://github.com/lovebrew/LovePotion/blob/master/source/modules/graphics/graphicsc.cpp#L393

### What was Expected?

https://github.com/love2d/love/blob/master/src/modules/graphics/Graphics.cpp#L448

### Code to Reproduce

```Lua
Dunno, I don't LOVE
```

### Console

Both

### Firmware Version(s)

*.*.*

### Custom Firmware Version

*.*.*

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
To clarify, this is because of restoring the graphics state when we had pushed “all”. It causes a validation state check. The previous font was stupidly not included.
