### ISSUE TITLE
[Bug]: 3ds crashes when trying to look for text?

### ISSUE THREAD

**Issue by wewewer123** [lovebrew/lovepotion#179]
### Software Version

2.4.0

### What Happened?

My 3ds fully crashed crash log is attached
(rename it to .dmp to open)
[crash_dump_00000000.dmp.txt](https://github.com/lovebrew/lovepotion/files/9418954/crash_dump_00000000.dmp.txt)

### What was Expected?

it's expected to display the text "I can't get up the nerve to ask right now. With a gulp, I decide to ask her later." the line before it crashes, and the next time you press a button (when it crashes) it's supposed to display "But I'm an indecisive person."

### Code to Reproduce

```Lua
it's multiple files, so here's a drive folder.

https://drive.google.com/drive/folders/1HPdbf6p_KmAxwUk-AsgE9iDVr57mPN9F?usp=sharing
```

### Console

Nintendo 3DS

### Firmware Version(s)

11.15.0-47E

### Custom Firmware Version

luma 2.0?

### Execution Method

Homebrew Menu

### Comment

I've no clue why it happens, because almost identical code which you can find [here](https://github.com/wewewer123/LOVE-VN-3DS) (the "TestGame" folder) works fine.

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Hm, I wonder if the text fixes that were contributed to citro2d would fix this issue. Let me check some things and I'll reply in a bit.

**Comment by TurtleP** [comment]
Okay, found a build which has a few fixes recently done, mainly a fix with text stuff in citro2d. Let me know if anything changes. This is the 3dsx, so you'll have to run it in the game folder. 

https://cdn.discordapp.com/attachments/479042864538714120/999786062626951208/LOVEPotion.3dsx

**Comment by wewewer123** [comment]
It seems to have fixed it, although it still isn't behaving correctly but that could just be my code, I'll let you know if it's still bugged.

**Comment by wewewer123** [comment]
Hi, me again, it seems to still be doing something weird, whilst this could still be my code, it worked correctly on the other test. It's also still correctly displaying for what number (sentence) it's looking for, it's just not displaying that at all for the first two (the one still is blank, and the one it crashed on is showing text it shouldn't read) could you please try running it/quickly look at the code to see if I messed something up or if it's still bugged.

**Comment by wewewer123** [comment]
> it's just not displaying that at all for the first two (the one still is blank, and the one it crashed on is showing text it shouldn't read)

after the one it crashed on before it continues as it should

**Comment by TurtleP** [comment]
I'm not sure what you mean by, "it's showing text it shouldn't read". Could you provide an example?

I also don't know if I'll be able to do much debugging this week, might be able to this weekend.

**Comment by wewewer123** [comment]
I made the program look for specific text by numbers(you'll know what I mean when you read the script.txt file that's on the drive/repo), but when it reads 105 it gives blank, and with 106 it gives a mix of 9, 10 and 11 whilst it literally looks for and should give 106. (Although now that I think about it there's a slight chance that I messed up my code and that somehow it gave no error, I'll reply again tmrw to let you know if I can fix it works)

**Comment by wewewer123** [comment]
It is indeed my code being wrong, as for the crash, that was probably related to the fact that because of my messed up code, it loaded 100 to 200 characters onto screen.
