### ISSUE TITLE
[Bug]: Latest version can not work on switch

### ISSUE THREAD

**Issue by iamcco** [lovebrew/lovepotion#185]
### Software Version

2.4.0

### What Happened?

Build hello word example can not work on switch with latest version (2.4.0) of LOVEPotion. I find it works well replace with old  version v2.3.2.

### What was Expected?

It should works on switch with latest version (2.4.0) of LOVEPotion.

### Code to Reproduce

```Lua
function love.draw()
    love.graphics.print('Hello World!', 200, 120)
end

-- we need to quit the app when a button is pressed
function love.gamepadpressed(joystick, button)
    love.event.quit()
end
```

### Console

Nintendo Switch

### Firmware Version(s)

15.0

### Custom Firmware Version

AMS 14.0

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
I'll take a look. I've not had any issues with 2.4.0 myself. Could you please elaborate on everything? Your prior issue on the other repository did mention it happened after some time.

**Comment by iamcco** [comment]
1. download the 2.4.0 from release page.
2. my project struct:

```
switch-backup/
  ├── game
  │   └── main.lua
  └── lovebrew.toml
```

3. build with command `lovebrew build`
4. copy `build/switch-backup.nro` to console's `/switch` directory.
5. run `switch-backup.nro` from the Homebrew menu.

The screen become black for a while then report error "The Software Was Closed Because An Error Occurred".  I find it if replace with old version (2.3.2) then rebuild the project and it works well.

**Comment by iamcco** [comment]
If I copy it (2.4.0) to console's `/switch/LOVEPotion/` with my `game` directory and that it runs well. This error only happen when running app which using `lovebrew build` command to build.

**Comment by TurtleP** [comment]
Definitely weird. I ran 2.4.0 yesterday (accidentally when trying to test 3.0). It ran perfectly fine.

I doubt that it's not finding the shaders when bundling, as I definitely did test lovebrew extensively.

Could you try using a game folder next to the default nro and see if that runs?

**Comment by iamcco** [comment]
> Could you try using a game folder next to the default nro and see if that runs?

As my comment above, it runs well with this way.

**Comment by TurtleP** [comment]
It might actually be an issue with LÖVEBrew then, hm. Weird. Try using 0.6.0, it's not fully released just yet, but you can get it from GitHub Actions, just download the artifact bundle for your OS. It does have a bit of extra setup, like needing `hbupdater`, but aside from that is fairly straightforward.

Although give me a bit to double check that I did implement Switch-related matters on that. I'm fairly certain I did, but I want to be sure.

**Comment by TurtleP** [comment]
Yeah, it does have support for bundling and all that for Switch in 0.6.0. Should be good to go. You'll also need to provide the nro binary instead of elf file as one of the major changes.

I do plan on making 0.6.0 available today or sometime this week, though.

**Comment by iamcco** [comment]
Test lovebrew 0.6.0 and LOVEPotion and it works well. Thanks!

**Comment by TurtleP** [comment]
Awesome, glad to hear!
