### ISSUE TITLE
[Code Health]: Graphics Module Cleanup

### ISSUE THREAD

**Issue by TurtleP** [lovebrew/lovepotion#194]
### Details

Discussed in https://github.com/lovebrew/lovepotion/discussions/193

### Solution

Make `Graphics<Console::ALL>` default implement for the Switch and Wii U code for primitive rendering, then the 3DS will have its own derived class to do its own thing. Furthermore, move the Switch DrawCommand struct to its own file so that the prior mentioned Graphics class can make use of it.

### Additional Context

N/A

**Comment by DexSpecial** [comment]
I agree
