### ISSUE TITLE
[Bug]: Get3D/get3DDepth

### ISSUE THREAD

**Issue by wewewer123** [lovebrew/lovepotion#199]
### Software Version

3.0-pre4

### What Happened?

the function Get3D returned true, even with my slider all the way down. As for get3DDepth, it throws the error: "[love "callbacks.lua"]:305:
Error: main.lua:256: attempt to call field 'get3DDepth' (a nil value)
stack traceback:
	[love "boot.lua"]:439: in function 'get3DDepth'
	main.lua:256: in function 'draw'
	[love "callbacks.lua"]:279: in function <[love "callbacks.lua"]:242>
	[C]: in function 'xpcall'
"

### What was Expected?

Get3D should only return true when the 3d mode is on, and Get3DDepth should give with a value 0-1 the depth slider position.

### Code to Reproduce

```Lua
function love.draw(Screen)
if love.graphics.get3D() then
love.graphics.printf(love.graphics.get3DDepth())
end
end
```

### Console

Nintendo 3DS

### Firmware Version(s)

11.15.0-47E (both 3dsxl and new3dsxl)

### Custom Firmware Version

Luma3DS v11.0-3gxldr (new3dsxl), Luma3ds v10.2.1 (3dsxl)

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Could you try `love.graphics.getDepth()`? I believe I had renamed it for 3.0, so apologies on the confusion.

**Comment by wewewer123** [comment]
That indeed fixes that issue, but I'm still confused about the Get3D function, does that tell you if it's a 2ds/3ds or if 3d mode is on?

**Comment by TurtleP** [comment]
Yeah get3D returns whether 3d mode is enabled and set3D can enable/disable it.

**Comment by wewewer123** [comment]
Ah, I thought it meant as in 3d slider position, thankyou for clearing that up.

Anyway I'll close this issue now.
