### ISSUE TITLE
[Bug]: Touch release triggers love.touchpressed instead of love.touchreleased

### ISSUE THREAD

**Issue by rednorka** [lovebrew/lovepotion#212]
### Software Version

3.0 Pre-Release 6

### What Happened?

When touch release happens, love.touchpressed is triggered instead of love.touchreleased. (Touch press is unaffected)

Tested only on Nintendo 3DS (New 2DS XL)

### What was Expected?

On touch release, love.touchreleased should be executed.

### Code to Reproduce

```Lua
-- On singular press:
-- - intended: "waiting... press! release! "
-- - what happens: "waiting... press! press! "
test = "waiting... "

function love.draw()
	love.graphics.print(test)
end

function love.touchpressed()
	test = test.."press! "
end

function love.touchreleased()
	test = test.."release! "
end
```

### Console

Nintendo 3DS

### Firmware Version(s)

11.17.0-50E

### Custom Firmware Version

13.0.2

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
This should be fixed with 3b25351. You can try out the GitHub Action artifact once it's done.
