### ISSUE TITLE
[Bug]: Cannot seem to open on Wii U (both HL and Aroma)

### ISSUE THREAD

**Issue by val-int1** [lovebrew/lovepotion#218]
### Software Version

3.0

### What Happened?

Launching the .elf from Homebrew Launcher (under Tiramisu) shows a "Not enough memory" message.
Launching the .wuhb with Aroma seems to work at first, but it instantly goes back to the Wii U menu.
The folder structure is as follows:
```
sdmc:/wiiu/apps/LOVEPotion/
  - lovepotion.elf
  - lovepotion.wuhb
  - game/
    - main.lua
```
Under Tiramisu:

https://github.com/lovebrew/lovepotion/assets/25990664/deabba37-4cfe-4bbe-bce4-1b6d434c74a6

Under Aroma:

https://github.com/lovebrew/lovepotion/assets/25990664/6523bc5f-2bad-422f-851a-9b3e85e3d5df

### What was Expected?

LÖVE Potion would open at least on the "no game" screen

### Code to Reproduce

```Lua
N/A
```

### Console

Nintendo Wii U

### Firmware Version(s)

5.5.5E

### Custom Firmware Version

EnvironmentLoader 0.2 + Tiramisu 0.1.2 / Aroma Beta-16

### Execution Method

Other

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Only Aroma is supported for Wii U. I don't know the contents of your game, so I can't really help.

**Comment by val-int1** [comment]
Ah ok, I didn't know that. Also I just tried again with a main.lua file containing only `function love.load() end`, so I guess [the previous one](https://github.com/lovebrew/lovepotion/files/13396892/main.lua.txt) did cause an issue, though I really don't know what could have caused it. Closing now as it is technically resolved (since nothing was really wrong).

**Comment by val-int1** [comment]
I just found out that the game leaves log files, and they seem to indicate a problem loading the font, and specifying the font in `love.graphics.setNewFont` makes the game no longer crash, although it doesn't display anything either. [boot.log](https://github.com/lovebrew/lovepotion/files/13397357/boot.log) [callbacks.log](https://github.com/lovebrew/lovepotion/files/13397358/callbacks.log)

**Comment by TurtleP** [comment]
I don't know what your code is doing. but please open a new issue relevant to the problem with your code and directory structure.
