### ISSUE TITLE
(3DS) Program hangs when suspending software / opening keyboard applet

### ISSUE THREAD

**Issue by ArsonousKnight52** [lovebrew/lovepotion#220]
### Software Version

3.0.0

### What Happened?

Upon suspending a love potion program, or opening the keyboard applet with love.keyboard.setTextInput, when the program is resumed the game logic functions, although nothing new is drawn, causing the game to stop visually updating and appear to freeze

### What was Expected?

Program resumes as normal after reopened / keyboard is closed

### Code to Reproduce

```Lua
input = "default"

function love.gamepadpressed()
    love.keyboard.setTextInput(true)
end

function love.textinput(text)
    input = text
end

function love.draw(screen)
    if screen == "bottom" then return end
    love.graphics.print(input)
end
```

### Console

Nintendo 3DS

### Firmware Version(s)

11.17.0-50E

### Custom Firmware Version

13.0.2

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Fixed with [5705bdb](https://github.com/lovebrew/lovepotion/commit/5705bdb7c832e612c56c86a4f50db71d549218bf)
