### ISSUE TITLE
[Bug]: joystick:getGamepadAxis righty is circlepad x and leftx is circlepad y

### ISSUE THREAD

**Issue by ArsonousKnight52** [lovebrew/lovepotion#223]
### Software Version

3.0

### What Happened?

when using love gamepad axis for getting the circlepad's x and y directions, you must get righty for the x value of the circlepad, and leftx for the y value of the circlepad.

### What was Expected?

leftx for circlepad x and lefty for circlepad y

### Code to Reproduce

```Lua
function love.load()
    joystick = love.joystick.getJoysticks()[1]
end

function love.update()
    x,y = joystick:getGamepadAxis( "righty" ), joystick:getGamepadAxis( "leftx" )
end

function love.draw()
    love.graphics.print(x, 0, 0)
    love.graphics.print(y, 0, 20)
end
```

### Console

Nintendo 3DS

### Firmware Version(s)

11.17.0-50E

### Custom Firmware Version

12.0.1

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Fixed with [5705bdb](https://github.com/lovebrew/lovepotion/commit/5705bdb7c832e612c56c86a4f50db71d549218bf)
