### ISSUE TITLE
[Bug]: None of the Showcase apps (from the wiki) work on the Switch

### ISSUE THREAD

**Issue by idanmiara** [lovebrew/lovepotion#228]
### Software Version

2.4.1 (also 3.0.1 debug)

### What Happened?

From the samples page https://lovebrew.org/#/showcase
https://shrikey.itch.io/lovestory - dead link
https://github.com/LukeZGD/DDLC-LOVE - work on Windows, but crashes on the switch (`cindy.lua:44: attempt to index local ParticleSystem (a nil value)`)
https://github.com/Stabyourself/mamono-sweeper-switch - nro files crashes (like https://github.com/lovebrew/lovepotion/issues/227)

The only sample game I could find that works on the Switch (and also on Windows):
https://github.com/fontire/LovePotionBook/tree/master/Working/Tetris

### What was Expected?

Maybe more working samples games ?

### Code to Reproduce

```Lua
see above
```

### Console

Nintendo Switch

### Firmware Version(s)

18.0.1

### Custom Firmware Version

AMS 1.7.0

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Honestly this isn't much of an issue that can be opened. It's up to the people who wrote those games to make sure they're up-to-date with LÖVE Potion. The showcase games *did* work at a time, but I guess not anymore, but in my opinion are still noteworthy. Ideally I could make note that the showcase items are more of things to show what people have done than functional things, worst case scenario, but the Wiki should be updated with things that are functional, if possible. 

That said, there's rarely anything showcased in the Discord server (there are several things posted, so no offense to anyone) but I haven't updated the showcase in a long while.

In the case of "DDLC-LOVE" that one.. ParticleSystem items were never supported (they *might* be available in 3.1.0, we'll see).

**Comment by idanmiara** [comment]
Thanks for your response.
I see your point, but I think there should be at least some basic showcase samples that do work and maintained alongside this repo (maybe in a single repo or multiple repos under https://github.com/lovebrew). They don't have to be full blown games, but at least something that beginners can learn some basics from, get motived by, and get the feeling of this platform - something more complex than Hello World.
I'm not sure how difficult it should be to maintain them between Love Potion versions and if that could be a burden, just my 2 cents :)

**Comment by TurtleP** [comment]
I had a repository like this once, but it didn't seem useful. This is why the Wiki links to the "How to LÕVE" book by sheepolution. Compatibility in 2.4+ is very well maintained these days.
