### ISSUE TITLE
[Bug]: can't clear Shape's mask / category

### ISSUE THREAD

**Issue by Royerson** [lovebrew/lovepotion#231]
### Software Version

3.0.1

### What Happened?

Running Shape:setMask or Shape:setCategory without arguments causes the following crash.
```
Error

main.lua:5: Values must be in range 1-16.


Traceback

[love "callbacks.lua"]:343: in function 'handler'
[C]: in function 'setMask'
main.lua:5: in function 'load'
[love "callbacks.lua"]:227: in function <[love "callbacks.lua"]:225>
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

### What was Expected?

Running these functions without arguments should simply clear the mask / category bits. This is the behavior (for Fixtures) in Love 11.5.

### Code to Reproduce

```Lua
function love.load()
	world = love.physics.newWorld()
	body = love.physics.newBody( world )
	shape = love.physics.newCircleShape( body, 0,0, 8 )
	shape:setMask()
end
```

### Console

Nintendo 3DS

### Firmware Version(s)

11.17.0-50U

### Custom Firmware Version

13.1.1

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by Nawias** [comment]
The code you provided is for LÖVE <0.8.0, not 11.5. Shapes don't have `:setMask()` or `:setCategory()` since 0.8.0.
Either way, LÖVE Potion targets LÖVE 12 API compatibility.

Please rewrite your code for LÖVE 12 and see if the problem persists. If so, provide the code here along with the error message.

**Comment by TurtleP** [comment]
If you want further information on the latest APIs for LÖVE, make sure you [read the Wiki](https://love2d.org/wiki/Shape).

**Comment by TurtleP** [comment]
Actually, reopening. It seems there's a discrepancy with how I wrote out getting the category bits compared to 12.0 which might be the cause for this. I might be able to get this done, might not, as I've been working on 3.1.0 for some time now.

**Comment by Royerson** [comment]
3.0.1 doesn't have physics fully implemented and uses a mixture of behavior from Love 12 and <0.8.0. I had assumed that part was intentional, and love.physics was just a work in progress.

**Comment by TurtleP** [comment]
Physics is fully implemented, not sure what you mean it's a mixture. I don't take any of the deprecated API call variants into account like 12 does. Regardless, I pushed the fix, please see if https://github.com/lovebrew/lovepotion/actions/runs/9454645289 fixes it.

**Comment by Royerson** [comment]
Trying to run love.physics.newFixture crashes with
```
attempt to call field 'newFixture' (a nil value)
```
Is that not something that should be implemented for 12?

Why is Shape:setMask mostly functional if it's removed since 0.8.0?

**Comment by Royerson** [comment]
I'm still confused by your comments, but that build fixed it perfectly. Thank you.

**Comment by TurtleP** [comment]
I mentioned that I don't implement the deprecated calls from LÖVE 12 into LÖVE Potion. In my opinion, it's better to have them removed sooner than later.

If you want some kind of Shape with a fixture, you likely want something like `love.physcis.newChain/Polygon/Edge/CircleShape. These are new in LÖVE 12.

**Comment by Royerson** [comment]
Okay I get it now. I looked into love 12 more and it removed fixtures and is kind of a mixture of love <0.8.0 and love 11 when it comes to physics.

Telling me to read the wiki isn't really helpful when it's still for love 11. So far I was figuring out how to use the physics module by reading the c++ for this project. Is there a better reference resource for love 12?

**Comment by TurtleP** [comment]
Yeah, I apologize. I was under the impression you had used something which was old and removed. It's been a while since I dealt with the physics module (and it is painful to use).

There is the LÖVE 12 change logs and source code too, but that might not really be more helpful than what I've provided.
