### ISSUE TITLE
[Bug]: 3.0 Wii U font issue

### ISSUE THREAD

**Issue by playsamay4** [lovebrew/lovepotion#232]
### Software Version

3.0

### What Happened?

calling love.graphics.newFont kicks you back to the wii u menu. in the boot.log, an error is written 
`Error: TrueType Font loading error: FT_New_Face failed: 0x21 (problem with font file?)`

[callbacks.log](https://pastebin.com/ueDrceNe)
[boot.log](https://pastebin.com/u0euQcqE)

### What was Expected?

Lovepotion to correctly show hello world

### Code to Reproduce

```Lua
function love.load()
    font = love.graphics.newFont(18)
end

function love.draw()
    love.graphics.setFont(font)
    love.graphics.print('Hello World!', 100, 100)
end

function love.gamepadpressed(joystick, button)
    love.event.quit()
end
```

### Console

Nintendo Wii U

### Firmware Version(s)

5.5.6U

### Custom Firmware Version

Tiramisu 0.2.0, Aroma Beta-20

### Execution Method

Wii U Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by not-nullptr** [comment]
this is a regression caused after [pre-release 5](https://github.com/lovebrew/lovepotion/releases/tag/3.0-pre5), as far as i can tell. also applies to #229

**Comment by TurtleP** [comment]
Closing in favor of opening a new issue relevant to the regression mentioned by @not-nullptr.
