### ISSUE TITLE
[Bug]: Not enough memory

### ISSUE THREAD

**Issue by ColdHorizon** [lovebrew/lovepotion#234]
### Software Version

3.0.1

### What Happened?

When i start love potion in the Homebrew menu, it says that it has not enough memory.

### What was Expected?

That the app should start.

### Code to Reproduce

```Lua
?
```

### Console

Nintendo Wii U

### Firmware Version(s)

5.5.6 U

### Custom Firmware Version

5.5.6 ?

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
LÖVE Potion is not meant to be ran through the homebrew menu on Wii U. You should be using Aroma's homebrew on home menu plugin and launch it from there. This is the only way to launch it.

Furthermore, there's an issue in the latest 3.0.x release that I tried debugging, but cannot track down where nothing is rendering. However, pre release 5 works.

I'm currently working on 3.1.0 which rewrites a lot of things and even has better rendering optimizations but isn't ready yet.

**Comment by ColdHorizon** [comment]
Thanks, i should install Aroma.
