### ISSUE TITLE
[Bug]: Something's not working on 3.0.1 (even latest pr debug build) on switch and 3ds

### ISSUE THREAD

**Issue by wewewer123** [lovebrew/lovepotion#236]
### Software Version

3.0.1

### What Happened?

nothing, completely nothing. System fully hangs and no logs get created no matter what I try.

### What was Expected?

run like it does on 3.0.0 release

### Code to Reproduce

```Lua
I still have to dig deeper, but as of rn can't figure it out (it giving no debug anywhere really complicates figuring out what is causing the issue), I rewrote a lot of code and it still hangs the system, for now all I can say is that both this: https://github.com/wewewer123/LOVE-VN-ENGINE and this https://github.com/wewewer123/LOVE-VN-ENGINE/tree/ScriptingRewrite lock up the system...
I still have to test the wiiu (gotta find display cable) and my normal 3ds xl, but it doesn't seem to be device specific.
(also the switch was borrowed so can't test that anymore)
```

### Console

Nintendo Switch, Nintendo 3DS

### Firmware Version(s)

new 3ds xl: 11.17.0-50E

### Custom Firmware Version

new 3ds xl: 13.0.2

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
I'm not fully understanding the context here. 3.0.1 itself works, so it has to be something specific in the code you wrote for your game.

However, if it worked on 3.0.0, then there is likely a regression. The problem is, I can't necessarily narrow this issue down without a minimal example.

For context, LÖVE Potion isn't meant to be a drop-in replacement for LÖVE itself. It is compatible, but usually projects are done from scratch or rewritten.

**Comment by wewewer123** [comment]
I know, this project however was always mainly meant for lovepotion, love itself was an afterthought, I'm still trying to narrow down what exactly is causing the issue, but it has to be a difference between 3.0.1 and 3.0.0.
I'll make a new comment when I figure out more, but it really complicates things if it doesn't log anything.

**Comment by TurtleP** [comment]
One new thing I added in 3.0.1 was the `console` config flag opens a TCP socket that waits until the user connects to it via (ip):8000. Do you have this flag enabled?

**Comment by Nawias** [comment]
I had a similar situation when trying to run my 2.4.x game on 3.0. I advise you to try to print-debug your code step by step and see where it breaks, especially early steps since it seems to lock up immediately. The new remote debugging feature is quite useful for that.

**Comment by Nawias** [comment]
@wewewer123 Have you been able to debug the issue further?

**Comment by wewewer123** [comment]
> One new thing I added in 3.0.1 was the `console` config flag opens a TCP socket that waits until the user connects to it via (ip):8000. Do you have this flag enabled?

Hey, sorry for the late reply...
But yes, I have that enabled in the config file, I'll try disabling it as soon as I get the chance (am not at home rn)

**Comment by wewewer123** [comment]
> I had a similar situation when trying to run my 2.4.x game on 3.0. I advise you to try to print-debug your code step by step and see where it breaks, especially early steps since it seems to lock up immediately. The new remote debugging feature is quite useful for that.

I had to adjust my code a decent bit between 2.4 and 3.0.0. There is no drag&drop solution as it went from love2d 11.x to 12 and that changes a few functions.
