### ISSUE TITLE
[Feature Request]: Is lan multiplayer possible?

### ISSUE THREAD

**Issue by nycki93** [lovebrew/lovepotion#239]
### Enhancement Details

I couldn't find this on the wiki. Is it possible to do lan multiplayer like in 3ds native titles?

### Solution

Either give an example of lan multiplayer code or explain why it isn't possible. Thanks!

### Additional Context

n/a

**Comment by TurtleP** [comment]
The closest you can get is using LuaSocket. Implementing download play would not really be ideal as it breaks compatibility with regular LÖVE, which I avoid to the best I can (e.g. loading textures and fonts have a special format here).
