### ISSUE TITLE
[Bug]: can't stop the music on 3ds (console hangs)

### ISSUE THREAD

**Issue by christphe** [lovebrew/lovepotion#240]
### Software Version

3.0.1

### What Happened?

When calling stop on a source it hangs the console

### What was Expected?

It should stop the music

### Code to Reproduce

```Lua
love.load = function()
    local music = love.audio.newSource("assets/sound.ogg", "stream")
    music:play()
    music:stop();
    love.event.quit(0)
end
```

### Console

Nintendo 3DS

### Firmware Version(s)

11.17.0-50E

### Custom Firmware Version

13.2.1

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
This was already addressed in a commit a while back. You can get a newer binary from the GitHub Actions where it’s fixed. See: https://github.com/lovebrew/lovepotion/issues/237.

**Comment by christphe** [comment]
Wow and it wasn't even hard to find, sorry about that.
