### ISSUE TITLE
Investigate LuaJIT support.

### ISSUE THREAD

**Issue by TSnake41** [lovebrew/lovepotion#81]
In order to improve performance, add FFI support, it is desirable to add LuaJIT support.
(additionally, some LÖVE2D games expect a LuaJIT environment)

LuaJIT for 3DS has been tested in the past with the [LuaJIT test on the 3ds-next branch](https://twitter.com/TurtleP95/status/1056209620996419589)
Since that, LuaJIT for 3DS has been improved (bug fixing, improvements, FFI improved with SLDL (better support for ffi.cdef/ffi.load)
We now have a stable [2.1-2 version](https://gitlab.com/TSnake41/luajit-3ds/tags/2.1-2) that is stable enough to run a shell based on FFI (FFI with some ctrulib routines). *lunnyjit shell*

For the Switch, things improved a lot as we get able to run the nbody(50000) benchmark on a true Switch (thanks @<i></i>Dax). There is still stuff to test (e.g FFI), but things are supposed stable enough to run LovePotion.
We can test out the [2.1-test2 version](https://gitlab.com/TSnake41/luajit-switch/tags/2.1-test2) that potentially work.

**Comment by TurtleP** [comment]
I’ve spoken to @fincs and @WinterMute regarding this a few times. We could potentially do a pull request for the devkitPro pacman-packages repo to add LuaJIT, but we’d have to clean up how building works.

**Comment by WinterMute** [comment]
Did you actually read http://luajit.org/install.html

I see nothing there that even slightly suggests LuaJIT isn't supposed to be built using Makefile "on foreign platforms". On the contrary there are clear instructions for cross compiling.

Generally it would actually be good if people spoke to us **before** embarking on making packages like this. I have no idea why you all insist on trying to shoehorn things into one of our Makefiles instead of using the existing build framework - it makes any future maintenance work rather more difficult than it needs to be.

The code you've added to pretend static libs are dynamic ones is a bit of a mess too. There's some potential in the methodology but it needs careful handling.

**Comment by TurtleP** [comment]
Do you think we should have a git diff and patch what we need with that? Or is there more to it?

**Comment by WinterMute** [comment]
The install page has this to say :- 
> ### Hints for Distribution Maintainers
>The LuaJIT build system has extra provisions for the needs of most POSIX-based distributions. If you're a package maintainer for a distribution, please make use of these features and avoid patching, subverting, autotoolizing or messing up the build system in unspeakable ways.
>
>There should be absolutely no need to patch luaconf.h or any of the Makefiles. And please do not hand-pick files for your packages — simply use whatever make install creates. There's a reason for all of the files and directories it creates.

Bear in mind that part of what's special about devkitARM, devkitA64 and the libraries we provide is the work that we put into making our supported targets look like POSIX systems. This often means that conformant libraries can be compiled with no changes at all.

I'd be inclined to start with a standard cross build with FFI disabled then have a look & see where we go from there.

**Comment by TSnake41** [comment]
I manage to build libluajit.a from LuaJIT 2.1 source (in src/ directory) with this line (after 3dsvars.sh and devkitarm.sh rules are added) : 
```make XCFLAGS="-DLUAJIT_USE_SYSMALLOC" CFLAGS="" LDFLAGS="" LIBS="" HOST_CC="gcc -m32" HOST_CFLAGS="" HOST_LIBS="" HOST_LDFLAGS="" CROSS=arm-none-eabi- TARGET_SYS=OTHER libluajit.a```

**Comment by TuxSH** [comment]
> as we are on ARM which does not have NX bit so there is no "need" of mmap and stuff 

There actually is, but with CFW you have sufficient permissions to transition between RW and RX. There's is also a linear uncached rwx mapping but I don't think it's suitable for this use.

**Comment by WinterMute** [comment]
A true libdl can't be added, we don't have dynamic libs, nor are they particularly feasible in this environment. There isn't a cleaner and less hacky libdl with static libs.

**Comment by DavidBuchanan314** [comment]
Python ctypes FFI will also benefit from a pseudo-dynamic-linking implementation.

Of course, doing so is inherently hacky, but I do think we should investigate the least hacky way to do it.

I currently have something similar to sldl which "works" for python ctypes.

**Comment by TurtleP** [comment]
The underlying issue is still that we don’t have proper dynamic library capabilities, nor is it easy to do so with the given environments (3ds/switch). I don’t think we need any libdl stuff.

**Comment by TSnake41** [comment]
For some FFI features (most interesting ones), a libdl "implementation" or LuaJIT patching is required.
Otherwise, we end up in "no support" code.

https://github.com/LuaJIT/LuaJIT/blob/master/src/lj_clib.c#L261-L286

So LuaJIT features such as FFI C calls throw an error.
```lua
local ffi = require "ffi"

ffi.cdef [[
  void *malloc(size_t);
  void free(void *);
]]

-- allocate 512 bytes using system allocator
local ptr = ffi.C.malloc(512)
-- ...
ffi.C.free(ptr)
```
Even if platform limits this kind of feature (static linking means no way to load symbols dynamically), we can still define these symbols at compile-time (like I did in [sldl](https://gitlab.com/TSnake41/luajit-3ds/blob/master/sldl/sldl.h) which implements a fake libdl).
The problem in my implementation is that it requires additionnal code to be called to use FFI C library features (`sldl_setenv` to define a environment that is used to simulate a libdl).
We can do alternatives by using a external fake-libdl library instead of "embedding" a fake libdl in LuaJIT or by using a other architecture (implement differently clib stuff).

**Comment by TSnake41** [comment]
I managed to build LuaJIT directly from source and finally achieved to something "clean".
But it ends up with patches in build-manager to don't "install" LuaJIT executable, man pages, and some other miscellaneous stuff that is useless in the devkitpro environment and consider that we only want static library and include files.
https://gist.github.com/TSnake41/e9c446029524ce5aa629d552423e12de
(I use latest git version for testing in my case, changing to 2.0.5 or 2.1-beta3 could be done without too much troubles).

This PKGBUILD builds a clean but unfriendly to an eventually future "lua" package due to a possible include file collision.
```
$ pacman -Qli 3ds-luajit
Nom                      : 3ds-luajit
Version                  : 2.1.61464b0-1
Description              : Just-in-time compiler and drop-in replacement for Lua 5.1 (for Nintendo 3DS homebrew development)
Architecture             : any
URL                      : http://luajit.org/
Licences                 : MIT
Groupes                  : --
Fournit                  : --
Dépend de                : --
Dépendances opt.         : --
Requis par               : --
Optionnel pour           : --
Est en conflit avec      : --
Remplace                 : --
Taille installée         : 528,00 KiB
Paqueteur                : Unknown Packager
Compilé le               : ven. 26 avr. 2019 23:27:18
Installé le              : ven. 26 avr. 2019 23:27:36
Motif d’installation     : Explicitement installé
Script d’installation    : Non
Validé par               : --

3ds-luajit /opt/
3ds-luajit /opt/devkitpro/
3ds-luajit /opt/devkitpro/portlibs/
3ds-luajit /opt/devkitpro/portlibs/3ds/
3ds-luajit /opt/devkitpro/portlibs/3ds/include/
3ds-luajit /opt/devkitpro/portlibs/3ds/include/lauxlib.h
3ds-luajit /opt/devkitpro/portlibs/3ds/include/lua.h
3ds-luajit /opt/devkitpro/portlibs/3ds/include/lua.hpp
3ds-luajit /opt/devkitpro/portlibs/3ds/include/luaconf.h
3ds-luajit /opt/devkitpro/portlibs/3ds/include/luajit.h
3ds-luajit /opt/devkitpro/portlibs/3ds/include/lualib.h
3ds-luajit /opt/devkitpro/portlibs/3ds/lib/
3ds-luajit /opt/devkitpro/portlibs/3ds/lib/libluajit.a
```

**Comment by WinterMute** [comment]
Well, @TSnake41, rather than just chucking it in a gist & linking here why not PR it to https://github.com/devkitPro/pacman-packages instead?

I prefer working with release archives and using the checksums if possible rather than pulling in source via git. You also only need 3dsvars.sh, that pulls in devkitarm.sh by itself now. It can involve a bit less patching if you allow it to install the useless stuff in the staging directory & then delete it in the PKGBUILD.

**Comment by TurtleP** [comment]
This has been open for the past couple of years, going to close it for now. @TSnake41 if you happen to pick this back up, we could re-open this issue, but we would need this on 3DS, Switch, and Wii U.
