### ISSUE TITLE
love.physics support using Box2D

### ISSUE THREAD

**Issue by TSnake41** [lovebrew/LovePotion#98]
Box2D support may be not that hard to implement (nothing platform-specific) and is a part of love namespace (unlike enet).

Some games uses it and Box2D doesn't have issues regarding 3DS and Switch (Box2D is said supported on NDS so I don't see any issue)

Love2D implementation of love.physics : https://github.com/love2d/love/tree/master/src/modules/physics

**Comment by TurtleP** [comment]
Waiting for #147, almost finished, should be done today
